export const ERROR_KEYS = {
  USERNAME: 'username',
  EMAIL: 'email',
  PASSWORD: 'password',
  RATING: 'rating',
  COMMENT: 'comment',
  USERNAME_OR_EMAIL: 'usernameOrEmail',
  NAME: 'name',
  SUBJECT: 'subject',
  MESSAGE: 'message',
  ADDRESS: 'address',
  ORDER_NOTES: 'orderNotes',
  PHONE: 'phone',
  FULL_NAME: 'fullName',
  PRICE: 'price',
  DESCRIPTION: 'description',
  CATEGORY_ID: 'category_id',
  STOCK_QUANTITY: 'stockQuantity',
  DISCOUNT_PERCENTAGE: 'discountPercentage',
  DEAL_END_TIME: 'dealEndTime'
} as const
